/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://dowf7hr66fcvzelmqopk4def64.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fgyb4r3v4ndado4bwmks5f7pi4",
    "aws_cognito_identity_pool_id": "us-east-1:16967257-6421-4a37-9d2d-555cc4241a1e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3ArKWFKou",
    "aws_user_pools_web_client_id": "5fq16m8fmmjm5dcukbfer89tdg",
    "oauth": {}
};


export default awsmobile;
